name: CI Admin + Deploy
on:
  workflow_dispatch:

jobs:
  run-admin-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # OK if no root package.json
      - name: Install repo deps (optional)
        run: npm ci || true

      # Ensure firebase-admin exists
      - name: Install firebase-admin
        run: npm i firebase-admin

      # --- Admin SDK sanity check (Firestore write) ---
      - name: Run Firebase Admin script
        run: node scripts/run-admin.cjs
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GOOGLE_CLOUD_PROJECT: priority-lead-sync

      # ---- Optional: Deploy (requires FIREBASE_TOKEN secret) ----
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Select project
        run: firebase use priority-lead-sync

      - name: Deploy Functions & Hosting
        run: firebase deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}