name: CI Admin (Repo Secrets)
on:
  workflow_dispatch:

jobs:
  run-admin:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || true
      - name: Run Firebase Admin script
        run: node scripts/run-admin.cjs
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GOOGLE_CLOUD_PROJECT: priority-lead-sync
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - run: firebase use priority-lead-sync
      - run: firebase deploy --only functions,hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
